### ISSUE TITLE
media/morgen.svg - undefined/unsupported image type, skipped

### ISSUE THREAD

**Issue by manishkvaish** [selifan/morgen#1]
First of all. Thank you very much for this wonderful class.

I am able to get every thing right except, this error:

"executing command: D:/app/inkscape/inkscape.exe -z media/morgen.svg -e greatApp/resources/_tmp_from_svg.png ... media/morgen.svg - undefined/unsupported image type, skipped executing command: D:/app/inkscape/inkscape.exe -z media/morgen.svg -e ios-greatApp/resources/_tmp_from_svg.png ... media/morgen.svg - undefined/unsupported image type, skipped"

 and thus replica of .svg file are not generated

I have got inkscape installed and put on the right path, as told

What could be the issue?

**Comment by selifan** [comment]
Try to call inkskape from shell, exactly the string You see in the log. (Run from folder where "media" folder with pictures is stored). And check a result. Does inkscape start ? If no, it means that it is installed in another path. If it runs, check error message from inkscape. Anyway, i think problem is somewhere outside of php script. Morgen just calls "external" shell command and then checks if "result" PNG image exists.

**Comment by manishkvaish** [comment]
Not working for  me, moreover my inkscape not able to open morgen.svg placed in  media folder.On web i found many link suggesting that .svg does not worki smooth for windows.Is it the problem ? as i am a windows user too.Thanks

**Comment by selifan** [comment]
Hm, it's strange, because this demo SVG file was created by me in inkscape for Windows!
Ok, just find (or create) any other SVG file and place it to the Media folder. Will it be converted ? If so, then my SVG might seems "corrupted" for Your version of inkscape. At least, on my PC, Windows 7 x64 (and latest available inkscape installed) everything from distributive works fine. 
And as i said, this is not a problem of morgen.php module - when You find SVG that is good enough for your inkscape (so it can convert to PNG), morgen.php will do it !

**Comment by manishkvaish** [comment]
I created a .svg image using inkscape on my PC,and tried to convert it using morgen code, but it is still not working.i am wondering what could be the issue.also ios-greatApp  is created, but no image is created there after executing morgen-demo.php.

**Comment by selifan** [comment]
I don't know how to help You. Try to reinstall inkscape.
Right now i've installed inkscape 0.91 x64 (from 7zip), downloaded morgen from github and run from demo folder. 
Here is a log, everythin is fine. No files in ios folder in Your case because of chosen file types in config (SVG only - see a project-greatApp.xml file)

```
Handling project: greatApp
greatApp/resources/drawable-mdpi\robot.png created OK
greatApp/resources/drawable-hdpi\robot.png created OK
greatApp/resources/drawable-xhdpi\robot.png created OK
greatApp/resources/drawable-xxhdpi\robot.png created OK
greatApp/resources/drawable-mdpi\button-001.jpg created OK
greatApp/resources/drawable-hdpi\button-001.jpg created OK
greatApp/resources/drawable-xhdpi\button-001.jpg created OK
greatApp/resources/drawable-xxhdpi\button-001.jpg created OK
executing command: D:/app/inkscape/inkscape.exe -z media/morgen.svg -e greatApp/resources/_tmp_from_svg.png ...
greatApp/resources/drawable-mdpi\morgen.png created OK
greatApp/resources/drawable-hdpi\morgen.png created OK
greatApp/resources/drawable-xhdpi\morgen.png created OK
greatApp/resources/drawable-xxhdpi\morgen.png created OK
executing command: D:/app/inkscape/inkscape.exe -z media/morgen.svg -e ios-greatApp/resources/_tmp_from_svg.png ...
ios-greatApp/resources/morgen.png created OK
ios-greatApp/resources/morgen@2x.png created OK

```

**Comment by selifan** [comment]
And i think You agree - it's not a morgen problem. So may be it's time to close this issue.

**Comment by manishkvaish** [comment]
I agree with the point that this is certainly not a morgen problem.So please close the issue.
anyway many thanks for your help.
